version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - 4015:443 

  db:
    image: postgres
    container_name: psql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Pa$$w0rd
      - POSTGRES_USER=appuser

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      -  5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root